import { TerminalType } from 'types/terminal'

export const MOCK_TERMINAL_TYPES: TerminalType[] = [
  {
    factory: null,
    note: null,
    minAvailable: -99999999,
    defOwner: null,
    available: -90003,
    mediaType: 'AMS-DEFAULT',
    attrs: [
      {
        nocopy: 0,
        attrValue: 'Option 1',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_TERMINAL_MODEL',
        key: 0,
      },
      {
        nocopy: 0,
        attrValue: 'AMS Demo ATM',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_NAME',
        key: 0,
      },
      {
        nocopy: 0,
        attrValue: '200101154240',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_POINT_CODE',
        key: 0,
      },
    ],
    institution: 'AMS Bank',
    vendor: 'test vendor',
    typeclass: 'POS',
    refAttrName: 'TLMS_SERIAL_NO',
    stateFlows: [
      {
        action: null,
        nextState: 'INSTALLED',
        state: 'INPRODUCTION',
        event: 'ASSEMBLE',
        manual: 0,
      },
      {
        action: null,
        nextState: 'IN-STOCK',
        state: 'IN-STOCK',
        event: 'CLOSE',
        manual: 1,
      },
      {
        action: null,
        nextState: 'IN-STOCK',
        state: 'INSTALLED',
        event: 'INSTOCK',
        manual: 1,
      },
      {
        action: null,
        nextState: 'UNINSTALLING',
        state: 'INSTALLED',
        event: 'UNINSTALL',
        manual: 1,
      },
      {
        action: null,
        nextState: 'INSTALLED',
        state: 'IN-STOCK',
        event: 'INSTALL',
        manual: 1,
      },
    ],
    group: 'DEFAULT',
  },
  {
    factory: null,
    note: null,
    minAvailable: -99999999,
    defOwner: null,
    available: -90003,
    mediaType: 'React',
    attrs: [
      {
        nocopy: 0,
        attrValue: 'Option 1',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_TERMINAL_MODEL',
        key: 0,
      },
      {
        nocopy: 0,
        attrValue: 'Name 2',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_NAME',
        key: 0,
      },
      {
        nocopy: 0,
        attrValue: '200101154240',
        history: 1,
        attrValueLarge: null,
        attrName: 'TLMS_POINT_CODE',
        key: 0,
      },
    ],
    institution: 'AMS Bank',
    vendor: null,
    typeclass: 'POS',
    refAttrName: 'TERMINAL_ID',
    stateFlows: [
      {
        action: null,
        nextState: 'INSTALLED',
        state: 'INPRODUCTION',
        event: 'ASSEMBLE',
        manual: 0,
      },
      {
        action: null,
        nextState: 'IN-STOCK',
        state: 'IN-STOCK',
        event: 'CLOSE',
        manual: 1,
      },
      {
        action: null,
        nextState: 'IN-STOCK',
        state: 'INSTALLED',
        event: 'INSTOCK',
        manual: 1,
      },
      {
        action: null,
        nextState: 'UNINSTALLING',
        state: 'INSTALLED',
        event: 'UNINSTALL',
        manual: 1,
      },
      {
        action: null,
        nextState: 'INSTALLED',
        state: 'IN-STOCK',
        event: 'INSTALL',
        manual: 1,
      },
    ],
    group: 'DEFAULT',
  },
]
